<?php

/**
 * @file
 * Installation functions for LiteSpeed Cache module.
 */

/**
 * Implements hook_install().
 */
function lite_speed_cache_install() {

    \Drupal\lite_speed_cache\Cache\LSCacheHelper::initHtaccess();
    \Drupal\lite_speed_cache\Cache\LSCacheHelper::initConfigs();

}


/**
 * Implements hook_uninstall().
 */
function lite_speed_cache_uninstall() {
    \Drupal\lite_speed_cache\Cache\LSCacheHelper::restoreHtaccess();
}
