lite_speed_cache.settings:
  type: config_object
  label: 'LiteSpeed Cache settings'
  mapping:
    lite_speed_cache:
      type: mapping
      mapping:
        esi_on:
          type: text
          label: 'Turn ESI On or Off.'
        max_age:
          type: text
          label: 'Define max age for public page cache.'
        max_age_private:
          type: text
          lable: 'Define max age for private page cache.'
        cache_status:
          type: text
          label: 'Cache is On or Off'
        debug:
          type: text
          label: 'Weather or not to log debug headers in log files of web server !'
block.settings.lite_speed_cache_block:
  type: block_settings
  label: 'LSCache block'
  mapping:
    lite_speed_cache_block_settings: